#!/bin/bash

OPENSSL_BIN="/usr/bin/openssl"

function to_filename {
  echo "$1" \
    | sed 's/\([^a-zA-Z0-9]\)/\-/g'
}

function create_root_ca {
  # create directories
  mkdir -p ca/root-ca/private ca/root-ca/db crl certs
  chmod 700 ca/root-ca/private

  # create database
  cp /dev/null ca/root-ca/db/root-ca.db
  cp /dev/null ca/root-ca/db/root-ca.db.attr
  echo 01 > ca/root-ca/db/root-ca.crt.srl
  echo 01 > ca/root-ca/db/root-ca.crl.srl

  # create CA request
  $OPENSSL_BIN req -new \
    -config etc/root-ca.conf \
    -out ca/root-ca.csr \
    -keyout ca/root-ca/private/root-ca.key

  # create CA certificate
  $OPENSSL_BIN ca -selfsign \
    -config etc/root-ca.conf \
    -in ca/root-ca.csr \
    -out ca/root-ca.crt \
    -extensions root_ca_ext
}

function create_signing_ca {
  # create directories
  mkdir -p ca/signing-ca/private ca/signing-ca/db crl certs
  chmod 700 ca/signing-ca/private

  # create database
  cp /dev/null ca/signing-ca/db/signing-ca.db
  cp /dev/null ca/signing-ca/db/signing-ca.db.attr
  echo 01 > ca/signing-ca/db/signing-ca.crt.srl
  echo 01 > ca/signing-ca/db/signing-ca.crl.srl

  # create CA request
  $OPENSSL_BIN req -new \
    -config etc/signing-ca.conf \
    -out ca/signing-ca.csr \
    -keyout ca/signing-ca/private/signing-ca.key

  # create CA certificate
  $OPENSSL_BIN ca \
    -config etc/root-ca.conf \
    -in ca/signing-ca.csr \
    -out ca/signing-ca.crt \
    -extensions signing_ca_ext
}

function create_server {
  COMMON_NAME="$1"
  FILE_NAME=$(to_filename "$COMMON_NAME")

  COMMON_NAME="$COMMON_NAME" \
  SUBJECT_ALTERNATIVE_NAME="DNS:$COMMON_NAME" \
  $OPENSSL_BIN req -new \
    -config etc/server.conf \
    -out certs/$FILE_NAME.csr \
    -keyout certs/$FILE_NAME.key

  $OPENSSL_BIN ca \
    -config etc/signing-ca.conf \
    -in certs/$FILE_NAME.csr \
    -out certs/$FILE_NAME.crt \
    -extensions server_ext
}

function create_email {
  COMMON_NAME="$1"
  EMAIL_ADDRESS="$2"
  FILE_NAME=$(to_filename "$COMMON_NAME")

  COMMON_NAME="$COMMON_NAME" \
  EMAIL_ADDRESS="$EMAIL_ADDRESS" \
  $OPENSSL_BIN req -new \
    -config etc/email.conf \
    -out certs/$FILE_NAME.csr \
    -keyout certs/$FILE_NAME.key

  $OPENSSL_BIN ca \
    -config etc/signing-ca.conf \
    -in certs/$FILE_NAME.csr \
    -out certs/$FILE_NAME.crt \
    -extensions email_ext
}

if [ "$1" == "init" ]; then
  create_root_ca
  create_signing_ca
fi

if [ "$1" == "create-server" ]; then
  create_server "$2"
fi

if [ "$1" == "create-email" ]; then
  create_email "$2" "$3"
fi

if [ "$1" == "deploy" ]; then
  COMMON_NAME="$2"
  SERVER="$3"
  REMOTE_DIR="$4"
  FILE_NAME=$(to_filename "$COMMON_NAME")

  ssh $SERVER "mkdir -p $REMOTE_DIR"
  cat certs/$FILE_NAME.crt | ssh $SERVER "cat - > $REMOTE_DIR/$FILE_NAME.crt"
  cat certs/$FILE_NAME.key | ssh $SERVER "cat - > $REMOTE_DIR/$FILE_NAME.key"
  cat certs/$FILE_NAME.crt ca/signing-ca.crt | ssh $SERVER "cat - > $REMOTE_DIR/$FILE_NAME.chained.crt"
  ssh $SERVER "chmod 600 $REMOTE_DIR/$FILE_NAME.key"
fi

exit 0
